---
# file: tasks/main.yml
- name: Install gnupg
  apt: name={{ item }} update_cache=yes state=present
  with_items:
  # Ændret af /bjhj
    - gnupg

- name: Install Solr deps
  apt: name={{ item }} state=present install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - unzip
    - tar

#- name: Install add-apt-repostory
#  become: yes
#  apt: name=software-properties-common state=latest
#
#- name: Add Oracle Java Repository
#  become: yes
#  apt_repository: repo='ppa:webupd8team/java'
#
#- name: Accept Java 8 License
#  become: yes
#  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
#
#- name: Install Oracle Java 8
#  become: yes
#  apt: name={{item}} state=latest
#  with_items:
#    - oracle-java8-installer
#    - ca-certificates
#    - oracle-java8-set-default

- include: solr.yml
  tags: solr

# vim: set sw=2 ts=2:
