---
language: python
python: "2.7"
sudo: required
dist: trusty

# environment variables
env:
  global:
    - ANSIBLE_INVENTORY=hosts
    - DEFAULT_SOLR_PORT=8983
    - DEFAULT_POSTGRES_PORT=5432
    - DEFAULT_APACHE_PORT=8080
    - DEFAULT_NGINX_PORT=80

# update indices, install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev python-pip gcc git curl

# update pip & install ansible from pip
install:
  - pip install --upgrade pip
  - pip install --upgrade ansible

# run tests
script:
  # Run syntax checks
  - "ansible-playbook tests/test.yml -i tests/hosts --connection=local --syntax-check"

  ## Test Solr Installation
  # Test solr role
  - "ansible-playbook tests/solr.yml -i tests/hosts --connection=local"

  # Curl solr web administration page & netcating its port
  - "/usr/bin/curl -I http://localhost:$DEFAULT_SOLR_PORT"
  - "echo | nc -v 127.0.0.1 $DEFAULT_SOLR_PORT"

  ## Test PostgreSQL Installation
  # Test postgresql role
  - "ansible-playbook tests/db.yml -i tests/hosts --connection=local"
  - "echo | nc -v 127.0.0.1 $DEFAULT_POSTGRES_PORT"

  ## Test Nginx, Apache & CKAN Installation
  - "ansible-playbook tests/ckan.yml -i tests/hosts --connection=local"

  # Test apache role
  - "echo | nc -v 127.0.0.1 $DEFAULT_APACHE_PORT"

  # Test nginx role
  - "echo | nc -v 127.0.0.1 $DEFAULT_NGINX_PORT"

  # Test ckan role
  # show response heads
  - "curl -Is http://127.0.0.1/ | grep 'HTTP/1.1 200 OK'"

# vim: set sw=2 ts=2:
