---
# file: db.yml

- hosts: db
  become: yes
#  user: provisioning
  user: bjhj
  vars_files:
    - vars/all.yml
  roles:
    - { role: postgresql, when: ansible_distribution == "Ubuntu", tags: postgresql }

  vars:
    ansible_become_pass: Rasmus12
# vim: set sw=2 ts=2:
